#ifndef __FINGERPRINT_H__
#define __FINGERPRINT_H__

struct  fingerprint_driver{

int (*compare_id)(void) ;
int (*probe)(struct spi_device *spi) ;
int (*remove)(struct spi_device *spi) ;
struct mt_chip_conf * fp_spi_conf;

};

enum fingerprint_cs{
	MTK_SPI_TEST_CS=0, // It's 0,because mtk_spi_test is used.

#if defined(CONFIG_FINGERPRINT_SUNWAVE_9551) ||defined(CONFIG_FINGERPRINT_SUNWAVECORP) || defined(CONFIG_FINGERPRINT_SUNWAVECORP_TEE) || defined(CONFIG_FINGERPRINT_SUNWAVE_TEE)
	FINGERPRINT_SUNWAVECORP_CS,
#endif
#ifdef CONFIG_FINGERPRINT_GF_MINANF_368_1214
	FINGERPRINT_GF_MINANF_368_1214_CS,
#endif
#ifdef CONFIG_FINGERPRINT_GF3208_GOODIX
	FINGERPRINT_GF3208_GOODIX_CS,
#endif
#ifdef CONFIG_FINGERPRINT_GF_GF5116M_1216
	FINGERPRINT_GF_GF5116M_1216_CS,
#endif
#ifdef CONFIG_FINGERPRINT_CS15XX
	FINGERPRINT_CS15XX_CS,
#endif
#if defined(CONFIG_FINGERPRINT_MICROARRAY) || defined(CONFIG_FINGERPRINT_MICROARRAY_TEE) || defined(CONFIG_FINGERPRINT_AFS120N) || defined(CONFIG_FINGERPRINT_MICROARRAY_A80T) || defined(CONFIG_FINGERPRINT_MICROARRAY_A80T_TEE)
	FINGERPRINT_MICROARRAY_CS,
#endif
#if defined(CONFIG_FINGERPRINT_GOODIX_GF5216) || defined(CONFIG_FINGERPRINT_GOODIX_GX556_TEE)
	FINGERPRINT_GOODIX_GF5216_CS,
#endif
#ifdef CONFIG_FINGERPRINT_DFS747
        FINGERPRINT_DFS747_CS,
#endif
      MAX_FINGER_CHIP_CS_NUMBER
};

#endif
