
# Each configuration option enables a list of files.

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include \
					-I$(srctree)/drivers/misc/mediatek/include/mt-plat -Wno-error

#obj-y += sunwavecorp.o platform.o misce.o mt6797_dts.o mt6797_dts_plat.o

obj-y += sunwavecorp.o
obj-y += platform.o
obj-y += misce.o
obj-y += mt6797_dts.o
obj-y += mt6797_dts_plat.o


