#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include \
					-I$(srctree)/drivers/misc/mediatek/include/mt-plat
# gf_5216

obj-y   +=  gf_spi.o 
