# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/AW9136/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  AW9136_ts_3Button.o

