
# Linux driver folder
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9271TB_hotknot/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XX_V26/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XX_V26/include/$(CONFIG_GTP_FIRMWARE)/
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XX_V26/include/config1/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XX_V26/include/$(CONFIG_GTP_CONFIG)/
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT9XX_V26/include/firmware1/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  gt9xx_driver.o
obj-y	+=  gt9xx_extents.o
obj-y	+=  gt9xx_update.o
obj-y	+=  goodix_tool.o

